version: "3.7"

services:
  one-shot_service_python:
    container_name: one-shot_service_python
    depends_on:
      - elasticsearch_test
    command: sh -c './wait-for 192.168.100.7:9200 -- cmd' # ожидаем

    image: local/python_elasticsearch
    networks:
      - elastic

  elasticsearch_test:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    container_name: elasticsearch_test
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic



volumes:
  elasticsearch:

networks:
  elastic:
    driver: bridge
